CREATE TABLE leave_request (
    request_id       NUMBER GENERATED BY DEFAULT AS IDENTITY
                     PRIMARY KEY,

    employee_id      NUMBER NOT NULL,
    leave_type       VARCHAR2(50) NOT NULL,
    from_date        DATE NOT NULL,
    to_date          DATE NOT NULL,
    number_of_days   NUMBER(5,2) NOT NULL,
    reason           VARCHAR2(1000),

    status           VARCHAR2(30) NOT NULL,

    manager_id       NUMBER,
    created_date     TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_date     TIMESTAMP DEFAULT SYSTIMESTAMP,

    CONSTRAINT leave_req_status_ck
        CHECK (status IN
        ('PENDING_MANAGER',
         'PENDING_HR',
         'APPROVED',
         'REJECTED'))
);
