CREATE TABLE leave_request_history (
    history_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id       NUMBER NOT NULL,
    action_by        NUMBER,
    action_role      VARCHAR2(30),
    action            VARCHAR2(30),
    old_status       VARCHAR2(30),
    new_status       VARCHAR2(30),
    comments         VARCHAR2(1000),
    action_date      TIMESTAMP DEFAULT SYSTIMESTAMP
);
